---
#interval = ticks
#20 ticks = 1 second
interval: 5
#Each message displayed in order
# 1 = message 1
1: "§l§bDEVINE §r§e- §bplay.devinepe.com §e- §b19132"
2: "§l§cDEVINE §r§e- §cplay.devinepe.com §e- §c19132"
3: "§l§6DEVINE §r§e- §6play.devinepe.com §e- §619132"
4: "§l§aDEVINE §r§e- §aplay.devinepe.com §e- §a19132"
...
